env:
  global:
    - CC_TEST_REPORTER_ID=cbb4ed82659da46058cffee3f587565a1615c9df7259b445b8b4229c520b1e7c

language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2

sudo: false

addons:
  code_climate:
    repo_token: cbb4ed82659da46058cffee3f587565a1615c9df7259b445b8b4229c520b1e7c

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install
